### ISSUE TITLE
Add more variants to card pool

### ISSUE THREAD

**Issue by stopfstedt** [ThronesDB/thronesdb-json-data#358]
Let's add the Kingsmoot Titles and cards from the upcoming "Hand of the King" Worlds 2020 side-event. 

For reference:
https://www.fantasyflightgames.com/en/news/2018/10/19/gt-i-will-take-my-crown/
https://www.fantasyflightgames.com/en/news/2019/12/20/dance-of-the-dragons/

**Comment by stopfstedt** [comment]
@ystros - is this something you would be interested in adding upstream to the throneteki-json-data repo as well?

**Comment by ystros** [comment]
@stopfstedt - Definitely have interest in this. I had actually already put this together locally over the holidays. I put it in the same card space as the Draft variant (00xxx card codes), picking up immediately after those cards.

Feedback welcome! https://github.com/throneteki/throneteki-json-data/pull/72
